### ISSUE TITLE
Does Not Compile On Xcode 10.2

### ISSUE THREAD

**Issue by danielkbx** [PromiseKit/CoreLocation#28]
Xcode 10.2 only supports Swift 4/5, so this extension does not compile until it is converted to Swift 4.

**Comment by mxcl** [comment]
You mean with Carthage? Please be specific.

**Comment by rsobolewski** [comment]
This issue is related to Xcode 10.2 because it only supports building projects written in Swift 4.0, 4.2 and 5.0. It's also effects Carthage because it uses new tools to build dependencies. If I change manually `Swift Language Version` to Swift 4.2 project compiles with success. I don't now if any additional actions are needed.

**Comment by danielkbx** [comment]
Sorry for just writing this issue without any further details.
I use the extension as a subproject in my project, because Carthage cannot build dependencies and I do not like to use CocoaPods.
However, in the end, Xcode compiles the sources and there is no Swift pre-4 compiler present anymore.
Therefore, the source code must be converted to at least Swift 4, if needed. @rsobolewski pointed out that there are no changes needed except for the used Swift Language Version.

Btw: what do you mean with "_it uses new tools to build dependencies_", @rsobolewski ?

**Comment by rsobolewski** [comment]
@danielkbx I mean command line tools from Xcode 10.2.

**Comment by mxcl** [comment]
I released 3.0.7 8 days ago which supports Xcode 10.2 and Swift 5, please update.
